services:
  manzolo-ubuntu:
    image: ${IMAGE_OWNER}/${IMAGE_NAME}:${IMAGE_TAG}
    container_name: ${CONTAINER_NAME}
    #runtime: nvidia

    #deploy:
    #  resources:
    #    reservations:        
    #      devices:
    #        - driver: nvidia
    #          count: 1
    #          capabilities: [gpu]
                
                
    stdin_open: true        # Permette l'interazione con la shell
    tty: true               # Mantiene la sessione aperta
    network_mode: host
    security_opt:
      - apparmor:unconfined
    shm_size: 512M
    devices:
      - /dev/input
      - /dev/uinput
      - /dev/snd
      #- /dev/nvidia0
      #- /dev/nvidiactl
      #- /dev/nvidia-modeset
    environment:
      # host UID/GID mapping
      - PUID=${UID:-1000}
      - PGID=${GID:-1000}
      # Wayland
      - WAYLAND_DISPLAY
      - XDG_RUNTIME_DIR=/run/user/${PUID:-1000}
      - DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - QT_QPA_PLATFORM=xcb
      - CONTAINER_USERNAME=${CONTAINER_USERNAME}
    volumes:
      # Wayland
      - /run/user/${PUID:-1000}/${WAYLAND_DISPLAY}:/run/user/${PUID:-1000}/${WAYLAND_DISPLAY}:rw
      #- /run/user/${PUID:-1000}/wayland:/run/user/${PUID:-1000}/wayland
      #- /tmp/.X11-unix:/tmp/.X11-unix:ro
      #- $HOME/.Xauthority:/${CONTAINER_USERNAME}/.Xauthority:rw
      # pulseaudio
      - /etc/machine-id:/etc/machine-id:ro
      - /run/user/${PUID:-1000}/pulse:/run/user/${PUID:-1000}/pulse:ro
      - $HOME/.config/pulse:/home/${CONTAINER_USERNAME}/.config/pulse
      # dbus
      - /run/user/${PUID:-1000}/bus:/run/user/${PUID:-1000}/bus:ro
      - /run/dbus:/run/dbus:ro
      - /run/udev/data:/run/udev/data:ro
      #- /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
      # inputs
      - /dev/input:/dev/input
